### ISSUE TITLE
ControlDir doesn't have correct label

### ISSUE THREAD

**Issue by ianfhunter** [UmSenhorQualquer/pyforms-gui#3]
I have been using ControlFile with success, but it doesn't seem that pyforms has an option to request a folder instead of a file. 

I guess this is a feature request, rather than an issue, but I don't know where else to file it.

**Comment by ianfhunter** [comment]
Nevermind, it is called ControlDir :man_facepalming:

**Comment by ianfhunter** [comment]
I do actually have an issue with it though.
Instead of the provided label, it says "TextLabel"
on Linux, Python 3.6

**Comment by MicBoucinha** [comment]
Hi,

I tried to reproduce your problem but here, and following the example (/tutorials/Controls4Docs/ControlDir.py), I get the proper label.

Can you show me what you tried to do? Perhaps I didn't understand your problem properly.

**Comment by ianfhunter** [comment]
Hi, I'll try to reproduce next time I'm at a PC, it'll be in the new year

**Comment by MicBoucinha** [comment]
Were you able to reproduce the problem?

**Comment by ianfhunter** [comment]
Hey, I did not get a chance. 
I am not actively working on the project using this, so while I do intend to - I keep forgetting.
Feel free to close and I can re-open if I can get you a minimal test case
