### ISSUE TITLE
Is there an updated doc on how to import CSS Styles?

### ISSUE THREAD

**Issue by taichatha** [UmSenhorQualquer/pyforms-gui#4]
I am trying to organize a bunch of text fields to look similar to the standard way how address forms are formatted. But I can't seem to find a way to import the css styles.

The examples use the master branch, but I am using v4.

**Comment by manuelmanso** [comment]
Hi,

I managed to import css styles using the v4 branch. You have create a css a file and then add its path to your settings like here: https://pyforms-gui.readthedocs.io/en/v4/getting-started/style-layout.html
If you don't have a settings file you should create one.

Then, in your program, just import conf and your settings file like this:

```
from confapp import conf
import settings
conf+=settings
```

**Comment by MicBoucinha** [comment]
I am closing this issue, please re-open it if you still have problems.
